name: HoloSlotsLite
main: com.antarescraft.kloudy.lite.slots.SlotsLite
version: 1.2
author: Kloudy
website: www.antarescraft.com

depend: [HoloGUIApi, Vault]

commands:
  slotslite:
    description: used to define commands for the SlotsLite plugin

permissions:
  slotslite.*:
    description: Gives a player access to all features and commands
    default: op
    children:
      slotslite.play: true
      slotslite.admin: true
  slotslite.play:
    description: Allows a player to play SlotsLite
    default: true
  slotslite.admin:
    description: Allows a player to admin level commands
    default: op