name: HoloSlotsLite
main: com.antarescraft.kloudy.lite.slots.SlotsLite
version: 1.0
author: Kloudy
website: www.antarescraft.com

depend: [HoloGUIApi, Vault]

commands:
  slotslite:
    description: used to define commands for the SlotsLite plugin

permissions:

  slotslite.play:
    description: Allows a player to play SlotsLite
    default: true